services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - chromadb
      - postgres

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - ./chroma_data:/chroma/chroma

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tahahasan01
      POSTGRES_PASSWORD: taha1234
      POSTGRES_DB: rag_bi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  chroma_data:
